// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJXS84ViQYOJoMj803Wp7coOU5OUcHYDw',
    appId: '1:725752089432:web:b24d05eb74d6583ff0f32d',
    messagingSenderId: '725752089432',
    projectId: 'gaz-rapide',
    authDomain: 'gaz-rapide.firebaseapp.com',
    storageBucket: 'gaz-rapide.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoTGF9ALd6Wj-RMkAtaK3RAntYav1idrI',
    appId: '1:725752089432:ios:9dd028addb6826e9f0f32d',
    messagingSenderId: '725752089432',
    projectId: 'gaz-rapide',
    storageBucket: 'gaz-rapide.firebasestorage.app',
    iosBundleId: 'com.example.gazrapide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoTGF9ALd6Wj-RMkAtaK3RAntYav1idrI',
    appId: '1:725752089432:ios:9dd028addb6826e9f0f32d',
    messagingSenderId: '725752089432',
    projectId: 'gaz-rapide',
    storageBucket: 'gaz-rapide.firebasestorage.app',
    iosBundleId: 'com.example.gazrapide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJXS84ViQYOJoMj803Wp7coOU5OUcHYDw',
    appId: '1:725752089432:web:5f0aa6748239138cf0f32d',
    messagingSenderId: '725752089432',
    projectId: 'gaz-rapide',
    authDomain: 'gaz-rapide.firebaseapp.com',
    storageBucket: 'gaz-rapide.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsgvOdIIR92p4MFKzNwdahNnU7PHxicXw',
    appId: '1:725752089432:android:a14f697fc9e3787ef0f32d',
    messagingSenderId: '725752089432',
    projectId: 'gaz-rapide',
    storageBucket: 'gaz-rapide.firebasestorage.app',
  );

}